schema_version = "1.0.0"

id = "squared_media_rig_ui"
version = "1.3.2"
name = "Squared Media Rig & UI"
tagline = "UI for controlling Squared Media's rigs in Blender"
maintainer = "Fxnarji <your.email@example.com>"
type = "add-on"

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

[permissions]
files = "for loading rig configurations and Skins"