name: Zip and Release project with version from TOML

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  zip_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create builds folder
        run: mkdir -p builds

      - name: Read version from blender_manifest.toml
        id: read_version
        run: |
          version=$(grep '^version' blender_manifest.toml | sed -E 's/version *= *"(.*)"/\1/')
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Read Name from blender_manifest.toml
        id: read_name
        run: |
          version=$(grep '^name' blender_manifest.toml | sed -E 's/name *= *"(.*)"/\1/')
          echo "name=$name" >> $GITHUB_OUTPUT

      - name: Prepare release variables
        id: vars
        run: |
          repo_name=$(basename $GITHUB_REPOSITORY)
          release_name="${{ steps.read_name.outputs.name }}_${{ steps.read_version.outputs.version }}"
          echo "release_name=$release_name" >> $GITHUB_OUTPUT
          echo "tag_name=${{ steps.read_version.outputs.version }}" >> $GITHUB_OUTPUT

      - name: Determine zip name
        id: zip_name
        run: |
          prefix="${{ steps.read_name.outputs.name}}"
          version="${{ steps.read_version.outputs.version }}"
          zip_name="$prefix $version.zip"
          echo "zip_name=$zip_name" >> $GITHUB_OUTPUT

      - name: Zip entire project excluding .git, .github/workflows, builds, and __pycache__
        run: |
          zip -r builds/${{ steps.zip_name.outputs.zip_name}}.zip . \
            -x ".git/*" \
            -x ".github/workflows/*" \
            -x "builds/*" \
            -x "**/__pycache__/*"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.vars.outputs.tag_name }}
          release_name: ${{ steps.vars.outputs.release_name }}
          draft: false
          prerelease: false

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: builds/${{ steps.zip_name.outputs.zip_name}}.zip
          asset_name: ${{ steps.zip_name.outputs.zip_name}}.zip
          asset_content_type: application/zip
