name: Zip lib folder

on:
  workflow_dispatch:

jobs:
  zip_lib:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create builds directory
        run: mkdir -p builds

      - name: Zip lib folder
        run: zip -r builds/test.zip lib
